WeblateOrg/helm

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Update to Weblate 4.1

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/templates/deployment.yaml
charts/weblate/values.yaml

Update to Weblate 4.2 and fix https://github.com/WeblateOrg/helm/pull/30

Weblate 4.2

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Before submitting a pull request, please ensure that:

Update to Weblate 4.3.1

---

.github/ct.yaml
.github/workflows/helm-test.yaml
.pre-commit-config.yaml
charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

It completely changed semantics without actually breaking build. That
made the automated CI merge pass while discarding all the testing
steps.

CI: Adjust to chart-testing-action@v2.0.0

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Update to Weblate 4.4

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Update to 4.4.1-1

---

.github/ct.yaml
.github/workflows/helm-test.yaml
charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Update to Weblate 4.5.2

---

charts/weblate/Chart.lock
charts/weblate/Chart.yaml
charts/weblate/README.md

Update postgresql and redis dependencies to get latest versions for new installs.
I have no clue if this can be simply increased or needs some upgrading docs/code.

Update postgresql and redis dependencies

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/templates/ingress.yaml
charts/weblate/values.yaml

Introdcues support for .spec.ingressClassName field in helm chart. Closes #139

Optional .spec.ingressClassName

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

Upgrade the Chart to provide [Weblate 4.11.2](https://github.com/WeblateOrg/weblate/releases/tag/weblate-4.11.2).

chart: Update to Weblate 4.11.2

---

.github/ct.yaml
.github/workflows/helm-test.yaml
charts/weblate/Chart.lock
charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/values.yaml

* Bump PostgreSQL dependency
* Use historic index for redis
* Bump versions
* Add nightly test job

Fixed using non-existing images

---

charts/weblate/README.md
charts/weblate/templates/_helpers.tpl
charts/weblate/values.yaml

This merge request add support for custom labels

Allow labels customization

---

charts/weblate/templates/deployment.yaml

deployment: Fix securityContext rendering

---

charts/weblate/README.md
charts/weblate/templates/ingress.yaml
charts/weblate/values.yaml

This MR allow to control pathType on ingress resources

Add control for pathType on ingress paths

---

charts/weblate/Chart.lock
charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/templates/deployment.yaml
charts/weblate/templates/secret.yaml
charts/weblate/values.yaml

This MR upgrade dependencies to latest version

Bump version for postgresql and redis chart

---

charts/weblate/README.md
charts/weblate/templates/deployment.yaml
charts/weblate/values.yaml

customizing various aspects of the application without
having to create a custom image (e.g. stylesheets, images, 
authentication providers, ...)
both mounts and volumes are rendered as raw object lists to allow mounting arbitrary data.
closes #161

add support for additional deployment volume mounts

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/templates/deployment.yaml
charts/weblate/templates/secret-env.yaml
charts/weblate/templates/secret.yaml
charts/weblate/values.yaml

Add podAnnotations and secretAnnotations

---

.github/workflows/helm-test.yaml

ci: use Python 3.11 for testing

---

charts/weblate/Chart.yaml
charts/weblate/README.md
charts/weblate/templates/deployment.yaml

fix(deployment): Liveness and Readiness probes configure options

---

charts/weblate/templates/deployment.yaml

The env vars are set wrongly in the chart

fix: Change the name of the auth env vars according to docs

---

.github/workflows/helm-test.yaml

Using the stable version (default) should be better approach for the testing.

chore(ci): remove helm pin in setup-helm action

---

charts/weblate/Chart.yaml

Use built-in customManagers:helmChartYamlAppVersions instead of custom logic.

chore: update renovate annotation
